# Generated by Django 6.0 on 2026-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
